language: cpp
before_script:
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install libdlib-dev -y
  - git clone https://github.com/davisking/dlib.git
  - cd dlib/dlib
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make install
  - cd ..
  - cd ..
  - cd ..
script:
- cmake .
- make all
- make package
deploy:
  provider: script
  skip_cleanup: true
  script: curl -T kkmeans-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uilivanovmirea:$BINTRAY_API_KEY "https://api.bintray.com/content/ilivanovmirea/kkmeans/kkmeans/$TRAVIS_BUILD_NUMBER/kkmeans-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"