language: cpp
before_script:
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install libdlib-dev -y
  - git clone https://github.com/davisking/dlib.git
  - cd dlib/dlib
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make install
  - cd ..
  - cd ..
  - cd ..
script:
- cmake .
- make all
- make package